#!/usr/bin/env bash
# PreToolUse(Edit|Write|MultiEdit): block edits to generated or locked files.
# Exit 2 = block the tool call and show stderr to Claude.
set -euo pipefail

command -v jq >/dev/null 2>&1 || exit 0
file=$(jq -r '.tool_input.file_path // empty')
[ -z "$file" ] && exit 0

# Collapse `.` and `..` segments without touching the filesystem (the file may not exist yet, and
# macOS bash 3.2 has no `realpath -m`), so `a/../bun.lock` can't slip past the patterns below.
normalize() {
  local IFS=/ part out=()
  for part in $1; do
    case "$part" in
      '' | .) ;;
      ..) [ ${#out[@]} -gt 0 ] && unset "out[$((${#out[@]} - 1))]" ;;
      *) out+=("$part") ;;
    esac
  done
  # bash 3.2 treats an empty array as unbound under `set -u`.
  if [ ${#out[@]} -eq 0 ]; then
    printf '/'
  else
    printf '/%s' "${out[@]}"
  fi
}

root=$(normalize "${CLAUDE_PROJECT_DIR:-$(pwd)}")
# Tools normally send absolute paths; resolve relative ones against the project root.
case "$file" in
  /*) ;;
  *) file="$root/$file" ;;
esac
file=$(normalize "$file")
rel="${file#"$root"/}"
reason=''

case "$rel" in
  packages/contract/openapi.json) reason='generated — run `bun run contract:generate`' ;;
  conformance/scenario.schema.json) reason='generated — run `bun run --filter @tula/conformance schema:generate`' ;;
  *.gen.ts) reason='generated by a code generator — rerun the generator' ;;
  apps/dashboard/src/components/ui/*) reason='shadcn primitive — wrap or extend it instead' ;;
  bun.lock) reason='managed by `bun add` / `bun remove`' ;;
  .env.example | */.env.example) ;;
  .env | .env.* | */.env | */.env.*) reason='local secrets file' ;;
  packages/db/migrations/*)
    # A migration already on develop has been applied somewhere — it is immutable.
    if git -C "$root" rev-parse --verify --quiet develop >/dev/null &&
      git -C "$root" cat-file -e "develop:$rel" 2>/dev/null; then
      reason='migration is already on develop — add a new migration instead'
    fi
    ;;
esac

if [ -n "$reason" ]; then
  echo "Blocked: $rel is protected ($reason). See AGENTS.md › Files you must NOT edit by hand." >&2
  exit 2
fi
exit 0
