import { join } from 'node:path'

// The scaffold tools hand out files of the example apps: the same files `create-tula` copies
// into a new project. This script reads them from `create-tula`'s templates (which its own
// sync keeps equal to `examples/`) and writes them into `src/scaffolds.gen.ts`, so the server
// carries them without reading a file at run time. `--check` fails instead of writing when
// the generated module is out of date (part of `bun run verify`, and a test).

const root = join(import.meta.dir, '..')
const templates = join(root, '..', 'create-tula', 'templates')
const target = join(root, 'src', 'scaffolds.gen.ts')

/** Which of a framework's template files make up each scaffold, by path inside the app. */
export const SCAFFOLD_SOURCES = {
  nextjs: {
    provider: ['app/layout.tsx', 'app/api/tula/[...tula]/route.ts'],
    protectedRoute: [
      'proxy.ts',
      'app/dashboard/page.tsx',
      'app/dashboard/session-check.tsx',
      'app/dashboard/actions.ts',
    ],
    signInPage: ['app/sign-in/page.tsx'],
  },
  'react-vite': {
    provider: ['src/auth-provider.tsx'],
    protectedRoute: ['src/protected.tsx'],
    signInPage: ['src/sign-in-page.tsx'],
  },
} as const

/**
 * The generated module's text, from the templates as they are now.
 *
 * @returns The contents `src/scaffolds.gen.ts` should have.
 */
export async function expectedModule(): Promise<string> {
  const out: Record<string, Record<string, { path: string; contents: string }[]>> = {}
  for (const [framework, kinds] of Object.entries(SCAFFOLD_SOURCES)) {
    const byKind: Record<string, { path: string; contents: string }[]> = {}
    for (const [kind, paths] of Object.entries(kinds)) {
      byKind[kind] = []
      for (const path of paths) {
        const contents = await Bun.file(join(templates, framework, 'app', path)).text()
        byKind[kind].push({ path, contents })
      }
    }
    out[framework] = byKind
  }
  return [
    '// Generated by `bun run --filter @tula/mcp generate` from create-tula’s templates, which',
    '// are generated from `examples/`. Do not edit: change the example, then run',
    '// `bun run --filter create-tula templates:sync`.',
    '',
    '/** The files of each scaffold, by framework and kind, exactly as the example apps have them. */',
    `export const SCAFFOLD_FILES = ${JSON.stringify(out, null, 2)} as const`,
    '',
  ].join('\n')
}

/**
 * Whether the committed module differs from what the templates say it should be.
 *
 * @returns `true` when it is out of date or missing.
 */
export async function scaffoldDrift(): Promise<boolean> {
  const file = Bun.file(target)
  return !(await file.exists()) || (await file.text()) !== (await expectedModule())
}

if (import.meta.main) {
  if (process.argv.includes('--check')) {
    if (await scaffoldDrift()) {
      process.stderr.write(
        '@tula/mcp scaffolds are out of date: run `bun run --filter create-tula templates:sync`\n'
      )
      process.exit(1)
    }
    process.stdout.write('@tula/mcp scaffolds are up to date\n')
  } else {
    await Bun.write(target, await expectedModule())
    process.stdout.write('wrote packages/mcp/src/scaffolds.gen.ts\n')
  }
}
