/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppInstanceAuditLogRouteImport } from './routes/_app/instance/audit-log'
import { Route as AppInstanceDiagnosticsRouteImport } from './routes/_app/instance/diagnostics'
import { Route as AppWWorkspaceIdIndexRouteImport } from './routes/_app/w.$workspaceId/index'
import { Route as AppWWorkspaceIdPProjectIdIndexRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/index'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/route'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdIndexRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/index'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdApiKeysRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/api-keys'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdAuditLogRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/audit-log'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdHooksRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/hooks'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdMessagesRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/messages'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdNativeAppsRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/native-apps'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdPasswordPolicyRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/password-policy'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdSessionsRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/sessions'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdSettingsRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/settings'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdSignInMethodsRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/sign-in-methods'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdSigningKeysRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/signing-keys'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdTextMessagesRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/text-messages'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdUsersIndexRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/users/index'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdUsersUserIdRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/users/$userId'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksIndexRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/webhooks/index'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdIndexRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/webhooks/$endpointId/index'
import { Route as AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdDeliveriesDeliveryIdRouteImport } from './routes/_app/w.$workspaceId/p.$projectId/e.$environmentId/webhooks/$endpointId/deliveries/$deliveryId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInstanceAuditLogRoute = AppInstanceAuditLogRouteImport.update({
  id: '/instance/audit-log',
  path: '/instance/audit-log',
  getParentRoute: () => AppRoute,
} as any)
const AppInstanceDiagnosticsRoute = AppInstanceDiagnosticsRouteImport.update({
  id: '/instance/diagnostics',
  path: '/instance/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkspaceIdIndexRoute = AppWWorkspaceIdIndexRouteImport.update({
  id: '/w/$workspaceId/',
  path: '/w/$workspaceId/',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkspaceIdPProjectIdIndexRoute =
  AppWWorkspaceIdPProjectIdIndexRouteImport.update({
    id: '/w/$workspaceId/p/$projectId/',
    path: '/w/$workspaceId/p/$projectId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteImport.update({
    id: '/w/$workspaceId/p/$projectId/e/$environmentId',
    path: '/w/$workspaceId/p/$projectId/e/$environmentId',
    getParentRoute: () => AppRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdIndexRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdApiKeysRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdAuditLogRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdAuditLogRouteImport.update({
    id: '/audit-log',
    path: '/audit-log',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdHooksRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdHooksRouteImport.update({
    id: '/hooks',
    path: '/hooks',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdMessagesRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdNativeAppsRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdNativeAppsRouteImport.update({
    id: '/native-apps',
    path: '/native-apps',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdPasswordPolicyRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdPasswordPolicyRouteImport.update({
    id: '/password-policy',
    path: '/password-policy',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdSessionsRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdSettingsRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdSignInMethodsRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdSignInMethodsRouteImport.update({
    id: '/sign-in-methods',
    path: '/sign-in-methods',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdSigningKeysRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdSigningKeysRouteImport.update({
    id: '/signing-keys',
    path: '/signing-keys',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdTextMessagesRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdTextMessagesRouteImport.update({
    id: '/text-messages',
    path: '/text-messages',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdUsersIndexRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdUsersUserIdRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksIndexRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksIndexRouteImport.update({
    id: '/webhooks/',
    path: '/webhooks/',
    getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
  } as any)
const AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdIndexRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdIndexRouteImport.update(
    {
      id: '/webhooks/$endpointId/',
      path: '/webhooks/$endpointId/',
      getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
    } as any,
  )
const AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdDeliveriesDeliveryIdRoute =
  AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdDeliveriesDeliveryIdRouteImport.update(
    {
      id: '/webhooks/$endpointId/deliveries/$deliveryId',
      path: '/webhooks/$endpointId/deliveries/$deliveryId',
      getParentRoute: () => AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/instance/audit-log': typeof AppInstanceAuditLogRoute
  '/instance/diagnostics': typeof AppInstanceDiagnosticsRoute
  '/w/$workspaceId/': typeof AppWWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$projectId/': typeof AppWWorkspaceIdPProjectIdIndexRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteWithChildren
  '/w/$workspaceId/p/$projectId/e/$environmentId/api-keys': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdApiKeysRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/audit-log': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdAuditLogRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/hooks': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdHooksRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/messages': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdMessagesRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/native-apps': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdNativeAppsRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/password-policy': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdPasswordPolicyRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/sessions': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSessionsRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/settings': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSettingsRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/sign-in-methods': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSignInMethodsRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/signing-keys': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSigningKeysRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/text-messages': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdTextMessagesRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdIndexRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/users/$userId': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdUsersUserIdRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/users/': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdUsersIndexRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksIndexRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdIndexRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/deliveries/$deliveryId': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdDeliveriesDeliveryIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/': typeof AppIndexRoute
  '/instance/audit-log': typeof AppInstanceAuditLogRoute
  '/instance/diagnostics': typeof AppInstanceDiagnosticsRoute
  '/w/$workspaceId': typeof AppWWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$projectId': typeof AppWWorkspaceIdPProjectIdIndexRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/api-keys': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdApiKeysRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/audit-log': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdAuditLogRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/hooks': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdHooksRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/messages': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdMessagesRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/native-apps': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdNativeAppsRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/password-policy': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdPasswordPolicyRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/sessions': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSessionsRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/settings': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSettingsRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/sign-in-methods': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSignInMethodsRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/signing-keys': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSigningKeysRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/text-messages': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdTextMessagesRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdIndexRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/users/$userId': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdUsersUserIdRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/users': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdUsersIndexRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksIndexRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdIndexRoute
  '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/deliveries/$deliveryId': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdDeliveriesDeliveryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/': typeof AppIndexRoute
  '/_app/instance/audit-log': typeof AppInstanceAuditLogRoute
  '/_app/instance/diagnostics': typeof AppInstanceDiagnosticsRoute
  '/_app/w/$workspaceId/': typeof AppWWorkspaceIdIndexRoute
  '/_app/w/$workspaceId/p/$projectId/': typeof AppWWorkspaceIdPProjectIdIndexRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteWithChildren
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/api-keys': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdApiKeysRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/audit-log': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdAuditLogRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/hooks': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdHooksRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/messages': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdMessagesRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/native-apps': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdNativeAppsRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/password-policy': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdPasswordPolicyRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/sessions': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSessionsRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/settings': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSettingsRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/sign-in-methods': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSignInMethodsRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/signing-keys': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSigningKeysRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/text-messages': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdTextMessagesRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdIndexRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/users/$userId': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdUsersUserIdRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/users/': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdUsersIndexRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksIndexRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdIndexRoute
  '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/deliveries/$deliveryId': typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdDeliveriesDeliveryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/instance/audit-log'
    | '/instance/diagnostics'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/p/$projectId/'
    | '/w/$workspaceId/p/$projectId/e/$environmentId'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/api-keys'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/audit-log'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/hooks'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/messages'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/native-apps'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/password-policy'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/sessions'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/settings'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/sign-in-methods'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/signing-keys'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/text-messages'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/users/$userId'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/users/'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/deliveries/$deliveryId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/'
    | '/instance/audit-log'
    | '/instance/diagnostics'
    | '/w/$workspaceId'
    | '/w/$workspaceId/p/$projectId'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/api-keys'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/audit-log'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/hooks'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/messages'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/native-apps'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/password-policy'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/sessions'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/settings'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/sign-in-methods'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/signing-keys'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/text-messages'
    | '/w/$workspaceId/p/$projectId/e/$environmentId'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/users/$userId'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/users'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId'
    | '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/deliveries/$deliveryId'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/'
    | '/_app/instance/audit-log'
    | '/_app/instance/diagnostics'
    | '/_app/w/$workspaceId/'
    | '/_app/w/$workspaceId/p/$projectId/'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/api-keys'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/audit-log'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/hooks'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/messages'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/native-apps'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/password-policy'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/sessions'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/settings'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/sign-in-methods'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/signing-keys'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/text-messages'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/users/$userId'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/users/'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/'
    | '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/deliveries/$deliveryId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instance/audit-log': {
      id: '/_app/instance/audit-log'
      path: '/instance/audit-log'
      fullPath: '/instance/audit-log'
      preLoaderRoute: typeof AppInstanceAuditLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/instance/diagnostics': {
      id: '/_app/instance/diagnostics'
      path: '/instance/diagnostics'
      fullPath: '/instance/diagnostics'
      preLoaderRoute: typeof AppInstanceDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/': {
      id: '/_app/w/$workspaceId/'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof AppWWorkspaceIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/p/$projectId/': {
      id: '/_app/w/$workspaceId/p/$projectId/'
      path: '/w/$workspaceId/p/$projectId'
      fullPath: '/w/$workspaceId/p/$projectId/'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId'
      path: '/w/$workspaceId/p/$projectId/e/$environmentId'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/'
      path: '/'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdIndexRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/api-keys': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/api-keys'
      path: '/api-keys'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/api-keys'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdApiKeysRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/audit-log': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/audit-log'
      path: '/audit-log'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/audit-log'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdAuditLogRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/hooks': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/hooks'
      path: '/hooks'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/hooks'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdHooksRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/messages': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/messages'
      path: '/messages'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/messages'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdMessagesRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/native-apps': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/native-apps'
      path: '/native-apps'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/native-apps'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdNativeAppsRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/password-policy': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/password-policy'
      path: '/password-policy'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/password-policy'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdPasswordPolicyRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/sessions': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/sessions'
      path: '/sessions'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/sessions'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSessionsRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/settings': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/settings'
      path: '/settings'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/settings'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSettingsRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/sign-in-methods': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/sign-in-methods'
      path: '/sign-in-methods'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/sign-in-methods'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSignInMethodsRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/signing-keys': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/signing-keys'
      path: '/signing-keys'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/signing-keys'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSigningKeysRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/text-messages': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/text-messages'
      path: '/text-messages'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/text-messages'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdTextMessagesRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/users/': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/users/'
      path: '/users'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/users/'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdUsersIndexRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/users/$userId': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/users/$userId'
      path: '/users/$userId'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/users/$userId'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdUsersUserIdRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/'
      path: '/webhooks'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksIndexRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/'
      path: '/webhooks/$endpointId'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdIndexRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
    '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/deliveries/$deliveryId': {
      id: '/_app/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/deliveries/$deliveryId'
      path: '/webhooks/$endpointId/deliveries/$deliveryId'
      fullPath: '/w/$workspaceId/p/$projectId/e/$environmentId/webhooks/$endpointId/deliveries/$deliveryId'
      preLoaderRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdDeliveriesDeliveryIdRouteImport
      parentRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute
    }
  }
}

interface AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteChildren {
  AppWWorkspaceIdPProjectIdEEnvironmentIdApiKeysRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdApiKeysRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdAuditLogRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdAuditLogRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdHooksRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdHooksRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdMessagesRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdMessagesRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdNativeAppsRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdNativeAppsRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdPasswordPolicyRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdPasswordPolicyRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdSessionsRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSessionsRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdSettingsRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSettingsRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdSignInMethodsRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSignInMethodsRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdSigningKeysRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdSigningKeysRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdTextMessagesRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdTextMessagesRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdIndexRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdIndexRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdUsersUserIdRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdUsersUserIdRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdUsersIndexRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdUsersIndexRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksIndexRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksIndexRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdIndexRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdIndexRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdDeliveriesDeliveryIdRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdDeliveriesDeliveryIdRoute
}

const AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteChildren: AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteChildren =
  {
    AppWWorkspaceIdPProjectIdEEnvironmentIdApiKeysRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdApiKeysRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdAuditLogRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdAuditLogRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdHooksRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdHooksRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdMessagesRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdMessagesRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdNativeAppsRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdNativeAppsRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdPasswordPolicyRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdPasswordPolicyRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdSessionsRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdSessionsRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdSettingsRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdSettingsRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdSignInMethodsRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdSignInMethodsRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdSigningKeysRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdSigningKeysRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdTextMessagesRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdTextMessagesRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdIndexRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdIndexRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdUsersUserIdRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdUsersUserIdRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdUsersIndexRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdUsersIndexRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksIndexRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksIndexRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdIndexRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdIndexRoute,
    AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdDeliveriesDeliveryIdRoute:
      AppWWorkspaceIdPProjectIdEEnvironmentIdWebhooksEndpointIdDeliveriesDeliveryIdRoute,
  }

const AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteWithChildren =
  AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute._addFileChildren(
    AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteChildren,
  )

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppInstanceAuditLogRoute: typeof AppInstanceAuditLogRoute
  AppInstanceDiagnosticsRoute: typeof AppInstanceDiagnosticsRoute
  AppWWorkspaceIdIndexRoute: typeof AppWWorkspaceIdIndexRoute
  AppWWorkspaceIdPProjectIdIndexRoute: typeof AppWWorkspaceIdPProjectIdIndexRoute
  AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute: typeof AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppInstanceAuditLogRoute: AppInstanceAuditLogRoute,
  AppInstanceDiagnosticsRoute: AppInstanceDiagnosticsRoute,
  AppWWorkspaceIdIndexRoute: AppWWorkspaceIdIndexRoute,
  AppWWorkspaceIdPProjectIdIndexRoute: AppWWorkspaceIdPProjectIdIndexRoute,
  AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRoute:
    AppWWorkspaceIdPProjectIdEEnvironmentIdRouteRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
