import { readdirSync, readFileSync, rmSync, statSync } from 'node:fs'
import { dirname, join, relative, resolve } from 'node:path'
import { ts } from 'ts-morph'
import { dedent, withSnippets } from './snippets'

// `bun run docs:generate` and `bun run docs:check`.
//
// Two things keep the documentation from drifting away from the code:
//
//   1. The SDK reference (docs/reference/*.md) is written from the JSDoc of every public entry
//      point of the packages below.
//   2. Code samples in docs/**/*.md and the READMEs are copied from files of the repository:
//      a block between `<!-- snippet: path#region -->` and `<!-- /snippet -->` is replaced by
//      that file (or by the lines between `// #region name` and `// #endregion` in it).
//
// `--check` writes nothing and fails when a file on disk differs from what would be written.
//
// The compiler API comes from ts-morph, pinned to an exact version in package.json: it bundles
// its own TypeScript, so the output does not change when the repository's compiler does, and
// nothing here needs the network.

const root = resolve(import.meta.dir, '..')

/** The packages with a reference page, in the order of the index. */
const PACKAGES = ['core', 'react', 'nextjs', 'admin', 'config', 'contract'] as const

const GENERATED_NOTE =
  '<!-- Generated by `bun run docs:generate` from the JSDoc in the package sources. Do not edit by hand. -->'

interface EntryPoint {
  /** What an application imports, e.g. `@tula/nextjs/server`. */
  specifier: string
  /** The source file, absolute. */
  file: string
}

interface PackageInfo {
  name: string
  description: string
  entries: EntryPoint[]
}

function readPackage(directory: string): PackageInfo {
  const manifest = JSON.parse(
    readFileSync(join(root, 'packages', directory, 'package.json'), 'utf8')
  ) as { name: string; description?: string; exports: Record<string, string> }
  const entries = Object.entries(manifest.exports)
    .filter(([, target]) => /\.tsx?$/.test(target))
    .map(([subpath, target]) => ({
      specifier: subpath === '.' ? manifest.name : `${manifest.name}/${subpath.slice(2)}`,
      file: join(root, 'packages', directory, target),
    }))
  return { name: manifest.name, description: manifest.description ?? '', entries }
}

function createProgram(files: string[]): ts.Program {
  return ts.createProgram(files, {
    target: ts.ScriptTarget.ESNext,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    jsx: ts.JsxEmit.ReactJSX,
    strict: true,
    noEmit: true,
    skipLibCheck: true,
    allowImportingTsExtensions: true,
    resolveJsonModule: true,
    types: [],
  })
}

/** A path as the docs show it: relative to the repository, with forward slashes. */
function shown(file: string): string {
  return relative(root, file).split('\\').join('/')
}

/** The text of a declaration up to its body, on as few lines as it was written. */
function withoutBody(declaration: ts.Node, body: ts.Node | undefined): string {
  const source = declaration.getSourceFile().text
  const end = body ? body.getFullStart() : declaration.getEnd()
  return source.slice(declaration.getStart(), end).trim()
}

function isHidden(member: ts.ClassElement): boolean {
  const modifiers = ts.canHaveModifiers(member) ? (ts.getModifiers(member) ?? []) : []
  return (
    modifiers.some(
      (modifier) =>
        modifier.kind === ts.SyntaxKind.PrivateKeyword ||
        modifier.kind === ts.SyntaxKind.ProtectedKeyword
    ) ||
    (member.name !== undefined && ts.isPrivateIdentifier(member.name))
  )
}

/** A class as its public surface: the heading line and every public member without its body. */
function classSignature(declaration: ts.ClassDeclaration): string {
  const source = declaration.getSourceFile().text
  const head = source.slice(declaration.getStart(), declaration.members.pos).trim()
  const members = declaration.members
    .filter((member) => !isHidden(member))
    .map((member) => {
      const body = (member as { body?: ts.Node }).body
      return `  ${dedent(withoutBody(member, body)).split('\n').join('\n  ')}`
    })
  return [head, ...members, '}'].join('\n')
}

/** What a constant is, as far as it can be said briefly. */
function constantSignature(declaration: ts.VariableDeclaration, checker: ts.TypeChecker): string {
  const name = declaration.name.getText()
  if (declaration.type) {
    return `const ${name}: ${declaration.type.getText()}`
  }
  const initializer = declaration.initializer
  if (initializer && (ts.isArrowFunction(initializer) || ts.isFunctionExpression(initializer))) {
    return `const ${withoutBody(declaration, initializer.body)}`.replace(/\s*=>\s*$/, ' => …')
  }
  // An inferred type is only worth printing when it is short: a Zod schema's runs to pages.
  const type = checker.typeToString(
    checker.getTypeAtLocation(declaration),
    declaration,
    ts.TypeFormatFlags.NoTruncation
  )
  return type.length <= 100 && !type.includes('\n') ? `const ${name}: ${type}` : `const ${name}`
}

interface Shown {
  kind: string
  code: string
}

function describe(declaration: ts.Declaration, checker: ts.TypeChecker): Shown | undefined {
  if (ts.isFunctionDeclaration(declaration)) {
    return { kind: 'function', code: withoutBody(declaration, declaration.body) }
  }
  if (ts.isVariableDeclaration(declaration)) {
    return { kind: 'constant', code: constantSignature(declaration, checker) }
  }
  if (ts.isInterfaceDeclaration(declaration)) {
    return { kind: 'interface', code: declaration.getText() }
  }
  if (ts.isTypeAliasDeclaration(declaration)) {
    return { kind: 'type', code: declaration.getText() }
  }
  if (ts.isClassDeclaration(declaration)) {
    return { kind: 'class', code: classSignature(declaration) }
  }
  if (ts.isEnumDeclaration(declaration)) {
    return { kind: 'enum', code: declaration.getText() }
  }
  if (ts.isModuleDeclaration(declaration)) {
    return { kind: 'namespace', code: `namespace ${declaration.name.getText()}` }
  }
  return undefined
}

/** A tag's text as markdown. An `@example` that is not already fenced becomes a code block. */
function tagText(tag: ts.JSDocTagInfo): string {
  const text = ts.displayPartsToString(tag.text).trim()
  if (tag.name === 'example' && !text.includes('```')) {
    return `\`\`\`ts\n${text}\n\`\`\``
  }
  return text
}

const TAG_TITLES: Record<string, string> = {
  returns: 'Returns',
  throws: 'Throws',
  example: 'Example',
  deprecated: 'Deprecated',
  default: 'Default',
  see: 'See',
  remarks: 'Remarks',
}

function renderTags(tags: ts.JSDocTagInfo[]): string[] {
  const lines: string[] = []
  const parameters = tags.filter((tag) => tag.name === 'param')
  if (parameters.length > 0) {
    lines.push('**Parameters**', '')
    for (const parameter of parameters) {
      const text = ts.displayPartsToString(parameter.text).trim()
      const [, name = text, rest = ''] = /^(\S+)\s*(?:-\s*)?([\s\S]*)$/.exec(text) ?? []
      lines.push(`- \`${name}\`${rest ? `: ${rest.split('\n').join('\n  ')}` : ''}`)
    }
    lines.push('')
  }
  for (const tag of tags) {
    if (tag.name === 'param') {
      continue
    }
    const title = TAG_TITLES[tag.name] ?? `@${tag.name}`
    const text = tagText(tag)
    if (text.includes('\n') || text.startsWith('```')) {
      lines.push(`**${title}**`, '', text, '')
    } else {
      lines.push(`**${title}** ${text}`.trimEnd(), '')
    }
  }
  return lines
}

interface Reference {
  markdown: string
  exports: number
  undocumented: string[]
}

function renderEntry(entry: EntryPoint, program: ts.Program): Reference {
  const checker = program.getTypeChecker()
  const source = program.getSourceFile(entry.file)
  const module = source && checker.getSymbolAtLocation(source)
  if (!module) {
    throw new Error(`docs: ${shown(entry.file)} is not a module`)
  }
  const lines: string[] = [`## \`${entry.specifier}\``, '', `Source: \`${shown(entry.file)}\``, '']
  const undocumented: string[] = []
  const exported = checker
    .getExportsOfModule(module)
    .sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
  for (const symbol of exported) {
    const target = symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol
    const declarations = target.declarations ?? []
    const described = declarations
      .map((declaration) => ({ declaration, shown: describe(declaration, checker) }))
      .filter((item): item is { declaration: ts.Declaration; shown: Shown } => Boolean(item.shown))
    if (described.length === 0) {
      // Never a silent gap: an export the generator cannot place is a bug in the generator
      // or an import that did not resolve.
      throw new Error(`docs: cannot describe the export \`${symbol.name}\` of ${entry.specifier}`)
    }
    const kinds = [...new Set(described.map((item) => item.shown.kind))].join(' and ')
    const first = described[0] as { declaration: ts.Declaration; shown: Shown }
    const documentation = ts.displayPartsToString(target.getDocumentationComment(checker)).trim()
    if (!documentation) {
      undocumented.push(`${entry.specifier}: ${symbol.name}`)
    }
    lines.push(
      `### \`${symbol.name}\``,
      '',
      `_${kinds}_, defined in \`${shown(first.declaration.getSourceFile().fileName)}\``,
      ''
    )
    if (documentation) {
      lines.push(documentation, '')
    }
    lines.push('```ts', described.map((item) => dedent(item.shown.code)).join('\n\n'), '```', '')
    lines.push(...renderTags(target.getJsDocTags(checker)))
  }
  return { markdown: lines.join('\n'), exports: exported.length, undocumented }
}

/** Every reference page, by path relative to the repository. */
function referencePages(): { pages: Map<string, string>; undocumented: string[] } {
  const packages = PACKAGES.map(readPackage)
  const program = createProgram(packages.flatMap((info) => info.entries.map((entry) => entry.file)))
  const pages = new Map<string, string>()
  const undocumented: string[] = []
  const index: string[] = [
    GENERATED_NOTE,
    '',
    '# SDK reference',
    '',
    'One page per package, written from the JSDoc of everything its entry points export.',
    'To change a page, change the JSDoc and run `bun run docs:generate`; `bun run docs:check`',
    '(part of `bun run verify`) fails when a page no longer matches the sources.',
    '',
    '| Package | Entry points | Exports |',
    '| --- | --- | --- |',
  ]
  for (const info of packages) {
    const slug = info.name.replace('@tula/', '')
    const entries = info.entries.map((entry) => renderEntry(entry, program))
    const total = entries.reduce((sum, entry) => sum + entry.exports, 0)
    undocumented.push(...entries.flatMap((entry) => entry.undocumented))
    index.push(
      `| [\`${info.name}\`](${slug}.md) | ${info.entries
        .map((entry) => `\`${entry.specifier}\``)
        .join(', ')} | ${total} |`
    )
    pages.set(
      `docs/reference/${slug}.md`,
      `${[
        GENERATED_NOTE,
        '',
        `# \`${info.name}\``,
        '',
        info.description,
        '',
        ...entries.map((entry) => entry.markdown),
      ]
        .join('\n')
        .trimEnd()}\n`
    )
  }
  pages.set('docs/reference/README.md', `${index.join('\n')}\n`)
  return { pages, undocumented }
}

/** Markdown files that may hold snippets: docs/** (not the generated reference) and READMEs. */
function markdownFiles(): string[] {
  const found: string[] = []
  const skip = new Set(['node_modules', 'reference', 'dist', '.git', '.next', 'adr', 'design'])
  function walk(directory: string, depth: number): void {
    for (const name of readdirSync(directory).sort()) {
      const path = join(directory, name)
      if (statSync(path).isDirectory()) {
        if (!skip.has(name) && !name.startsWith('.') && depth < 4) {
          walk(path, depth + 1)
        }
      } else if (name.endsWith('.md')) {
        found.push(path)
      }
    }
  }
  walk(join(root, 'docs'), 0)
  for (const group of ['packages', 'examples', 'apps']) {
    for (const name of readdirSync(join(root, group)).sort()) {
      const readme = join(root, group, name, 'README.md')
      if (statSync(readme, { throwIfNoEntry: false })?.isFile()) {
        found.push(readme)
      }
    }
  }
  found.push(join(root, 'README.md'), join(root, 'conformance', 'README.md'))
  return found
}

function current(path: string): string | undefined {
  try {
    return readFileSync(join(root, path), 'utf8')
  } catch {
    return undefined
  }
}

const check = process.argv.includes('--check')
const { pages, undocumented } = referencePages()
const wanted = new Map(pages)
for (const file of markdownFiles()) {
  const path = shown(file)
  const text = readFileSync(file, 'utf8')
  const filled = withSnippets(root, text, path)
  if (filled !== text) {
    wanted.set(path, filled)
  }
}

// A reference page whose package or entry point is gone must go too.
const stale = readdirSync(join(root, 'docs', 'reference'), { withFileTypes: true })
  .filter((entry) => entry.isFile() && !pages.has(`docs/reference/${entry.name}`))
  .map((entry) => `docs/reference/${entry.name}`)

const changed = [...wanted].filter(([path, text]) => current(path) !== text).map(([path]) => path)

if (undocumented.length > 0) {
  console.error(
    `docs: ${undocumented.length} public export(s) have no JSDoc summary:\n${undocumented
      .map((name) => `  ${name}`)
      .join('\n')}`
  )
  process.exit(1)
}

if (check) {
  if (changed.length > 0 || stale.length > 0) {
    console.error(
      `docs: out of date (run \`bun run docs:generate\` and commit the result):\n${[
        ...changed,
        ...stale.map((path) => `${path} (no longer generated)`),
      ]
        .map((path) => `  ${path}`)
        .join('\n')}`
    )
    process.exit(1)
  }
  console.log(`docs: ${pages.size} reference pages and every snippet match the sources`)
} else {
  for (const path of changed) {
    await Bun.write(join(root, path), wanted.get(path) as string)
  }
  for (const path of stale) {
    rmSync(join(root, path))
  }
  console.log(
    `docs: wrote ${changed.length} file(s), removed ${stale.length}; ${pages.size} reference pages in ${shown(dirname(join(root, 'docs/reference/README.md')))}`
  )
}
